Dynamic tests

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -8,20 +8,51 @@ on:
       - main
   workflow_dispatch:
 jobs:
-  test-basic:
-    name: Test basic
+  build_matrix:
+    name: Build test matrix
     runs-on: ubuntu-latest
+    outputs:
+      paths: ${{ steps.paths.outputs.JSON_CONTENT }}
+    steps:
+      - name: Checkout the Git repository
+        uses: actions/checkout@v4
+      - name: Output matrix
+        id: paths
+        run: |
+          set -e
+          set -o pipefail
+          if [ ! -d tests ]; then
+            echo "Error: Failed to find tests directory"
+            ls -l
+            exit 1
+          fi
+          content=$(jq -ncR '[inputs]' <<< $(find tests -mindepth 2 -maxdepth 2 -type f -name VELBUILD | xargs dirname | xargs basename))
+          echo "$content"
+          echo 'JSON_CONTENT<<EOF' >> $GITHUB_OUTPUT
+          echo "$content" >> $GITHUB_OUTPUT
+          echo 'EOF' >> $GITHUB_OUTPUT
+  tests:
+    name: Tests
+    runs-on: ubuntu-latest
+    needs: build_matrix
     strategy:
       matrix:
-        path:
-          - tests/basic
+        path: ${{ fromJson(needs.build_matrix.outputs.paths) }}
+        driver:
+          - podman
+          - docker
+      fail-fast: false
     steps:
       - name: Checkout the Git repository
         uses: actions/checkout@v4
       - name: Run action
         uses: ./
         with:
-          path: ${{ matrix.path }}
+          path: tests/${{ matrix.path }}
+          driver: ${{ matrix.driver }}
       - name: Validate output
+        if: "!cancelled()"
         shell: bash
-        run: ${{ matrix.path }}/validate.sh
+        run: |
+          set -e
+          tests/${{ matrix.path }}/validate.sh
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -17,17 +17,57 @@ inputs:
     description: Version of vbuild to use
     required: false
     default: latest
+  driver:
+    description: Which driver to use. Can be podman or docker
+    required: false
+    default: podman
 runs:
   using: composite
   steps:
+    - name: Validate inputs
+      shell: bash
+      run: |
+        set -e
+        if [ "$driver" != 'podman' ] && [ "$driver" != 'docker' ];then
+          echo "Error: invalid driver: $driver"
+          exit 1
+        fi
+        if [ ! -d "$src_path" ];then
+          echo "Error: Path does not exist: $src_path"
+          exit 1
+        fi
+      env:
+        driver: ${{ inputs.driver }}
+        src_path: ${{ inputs.path }}
     - name: Download vbuild
       shell: bash
       run: |
         set -e
         curl \
-          'https://github.com/Eeems/vbuild/releases/download/${{ inputs.version }}/vbuild-vbuild-ubuntu' \
-          --output=/usr/local/bin/vbuild
+          --location \
+          'https://github.com/Eeems/vbuild/releases/${{ inputs.version }}/download/vbuild-vbuild-ubuntu' \
+          --output /usr/local/bin/vbuild
         chmod +x /usr/local/bin/vbuild
+        file /usr/local/bin/vbuild
     - name: Run vbuild
       shell: bash
-      run: vbuild -C "${{ inputs.path || '.' }}" "${{ inputs.action || "all" }}"
+      run: |
+        set -e
+        if [ "$driver" == 'podman' ];then
+          echo "Starting podman service..."
+          mkdir -p /run/user/"$UID"/podman
+          podman system service --time 0 unix:///run/user/"$UID"/podman/podman.sock &
+          tries=0
+          while [ ! -S /run/podman/podman.sock ] && [ $tries -lt 60 ];do
+            tries=$(( tries + 1 ))
+            sleep 0.1
+          done
+        fi
+        echo "Running vbuild..."
+        vbuild -C "${{ inputs.path || '.' }}" "${{ inputs.action || 'all' }}"
+        if [ "$driver" == 'podman' ];then
+          echo "Stopping podman service..."
+          kill $(jobs -p) || true
+        fi
+      env:
+        driver: ${{ inputs.driver }}
